### ISSUE TITLE
Smartthings integration

### ISSUE THREAD

**Issue by rogueturnip** [taligentx/dscKeybusInterface#19]
I don't have time right now to do this integration but if someone else has interest these guys released a bunch of device handlers for their implementation and it should be relatively simple to modify them to work with this design.
https://github.com/konnected-io/konnected-security

**Comment by taligentx** [comment]
Thanks, SmartThings integration would be useful.  I looked into this a few weeks ago and wasn't able to find a way to report when the alarm was triggered - from their forums, some of the third party SmartThings devs state that this part of the API is closed off except for paid partners like Scout/ADT, etc:

https://community.smartthings.com/t/getting-the-shm-status-through-the-api/41285/7

Do you know if Konnected is able to send triggered alarm states to Smart Home Monitor?  Otherwise it should be possible to get basic armed/disarmed states to SHM - the question will be if there's a useful purpose without notifications on the alarm being triggered.
