### ISSUE TITLE
ESP8266 broadcasting unwanted SSID

### ISSUE THREAD

**Issue by sj-louw** [taligentx/dscKeybusInterface#30]
The esp8266 sketches broadcast a unsecured network / SSID (Example: ESP_123456). This behaviour can and should probably be disabled by using `WiFi.mode(WIFI_STA);` in the setup routine of the sketch.

Example:
```
...
  WiFi.begin(wifiSSID, wifiPassword);
  WiFi.mode(WIFI_STA);
  while (WiFi.status() != WL_CONNECTED) delay(500);
...
```

**Comment by taligentx** [comment]
Thanks for the catch, I'm seeing the same issue and have updated the examples in the develop branch to explicitly set station mode.  

This may be a bug in the esp8266 Arduino library, per the [documentation](https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/station-class.html):

`Switching the module to Station mode is done with begin function.`

It seems odd that the esp8266 soft AP is active after the `begin` function, I'll take a closer look at the esp8266 library to see if this is expected behavior.
