### ISSUE TITLE
PC3000 Testing

### ISSUE THREAD

**Issue by b0bcarlson** [taligentx/dscKeybusInterface#303]
I am currently setting up Arduino Uno to a PC3000.
Ran the KeybusReader without issue using the instructions for classic wiring. Switching to the MQTT I am having some issues but I believe they are network related (struggling to connect to the MQTT server when it worked before wiring it). I will update when I have updates!

**Comment by b0bcarlson** [comment]
~~I was able to get it connected to MQTT and it shows in HA as disarmed, however I cannot seem to get anything else to work. No zones update in HA and attempting to arm from HA does not do anything. Guessing this is a MQTT config issue so I will continue to investigate~~ Disregard this, I forgot to enable the PC16 output

**Comment by b0bcarlson** [comment]
Update to this - I'm attempting to run the unlocker but getting stuck at any of the places it's checking the `dsc.status[0]` (zones are clear so it should continue). I'm not much of a C programmer but I'm trying my best to dig into what these statuses mean and why it might not be working.

**Comment by b0bcarlson** [comment]
I realized the unlocker is not compatible with the classic series, so I modified it to brute force and was able to get the installer code. Unfortunately I am having connection issues again, but I'm thinking things are still looking pretty good.

**Comment by b0bcarlson** [comment]
After continuing to mess around with this I have come up with a pattern:
- enabling PC16 output breaks networking (DHCP failures, MQTT connection issues)
- disabling PC16 output makes things almost work - pressing "Arm" triggers a single key press (instead of 4), but more importantly sensors don't seem to communicate correctly (shows most as unknown)
- disabling PC16 output and commenting out `#define dscClassicSeries` behaves similarly to the above except that the arm buttons do not trigger any key presses.

I found the "Status" example and it pretty much confirms my findings - it connects then does not display any messages after that.

I'll keep this ticket open for now in case anyone has any ideas. However, this is not my house and I will be moving in a week so I will not be able to test after that.

It should be noted that I am using a breadboard against recommendations as I would like to see if it even works before I solder.

**Comment by sfossen** [comment]
Have you tried [a modified version](https://github.com/taligentx/dscKeybusInterface/pull/296)?

**Comment by b0bcarlson** [comment]
Yes, actually I saw that yesterday and started testing it with much better luck. Still not perfect though; I moved the PC16 from 4 to 12 and the network issues stopped but when I use MQTT it seems to cause interference (breadboard probably). I haven't had much time to get further but I was going to try a few other modifications and see where they get me.

**Comment by sfossen** [comment]
Which version of the circuit did you use? The version I pointed you to was developed on a breadboarded circuit with optocouplers on an nodemcu v2.

**Comment by b0bcarlson** [comment]
Gotta close this out, with me moving at the end of this week I've run out of time to keep working on it :(

**Comment by kricon** [comment]
@b0bcarlson sorry that im late here,
- For PC3000 you need to use sfossen's PC3000 library, because PC3000 uses 3 bytes of keybus data (where PC1550/PC2550 have just two bytes and PC560 just one). 
- You also **need** to have `#define dscClassicSeries` **uncommented** for classic series to work. Otherwise, you will get false junk data and things just wont work as whole classic/powerseries structure is so different.
- I've had better luck with just twisting wires to resistors and transistor for quick bench-testing than using cheapo bad quality breadboards before soldering onto protoboard. You can connect 1k resistor from PGM to AUX+ directly on PC300.
- PC16 out **must** be enabled (section 19, option 4) aswell as PGM out set to Strobe output (section 28, second digit 8).
- For unlocker sketch to work with classic series, you must use sfossen's library, uncommented define and have system in ready state. Unlocker example works fine for me on PC1550 and I belive that sfossen also tested it with his PC3000 panel. Don't forget to ground out PC16 pin.
- Try `KeybusReader` sketch (from sfossen's PC3000 library) through USB serial and post logs here if things doenst work as it should.
- On Arduino IDE, if you have both _dscKeybusInterface_ and _dscKeybusInterface_PC3000_ libraries in Documents/Arduino folder, PC3000 example will use source data from regular _dscKeybusInterface_. Delete or temorary move _dscKeybusInterface_ folder from Documents/Arduino/libraries for PC3000 library to work.
